packages:
  - packages/*

blockExoticSubdeps: true

linkWorkspacePackages: true

minimumReleaseAge: 1440

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 43800 # 1 month

publishBranch: main

strictDepBuilds: true

savePrefix: ''

saveWorkspaceProtocol: rolling

optimisticRepeatInstall: true

verifyDepsBeforeRun: install

onlyBuiltDependencies:
  - esbuild

allowBuilds:
  esbuild: false
