import type { Command } from 'commander';
import type { z } from 'zod';

import type { ProxyPolicy } from '#src/config/proxy-policy.js';
import type { SandboxConfig } from '#src/config/sandbox.js';
import type { UserConfig } from '#src/config/user.js';
import type { SandboxEntry } from '#src/state/index.js';

/**
 * One command a plugin wants the orchestrator to run inside the VM after the
 * iptables lockdown — i.e. only the host proxy is reachable. argv-only (no
 * shell) keeps token-placeholder commands like
 * `git config http.<repo>.extraHeader 'Authorization: Bearer <PLACEHOLDER>'`
 * injection-safe.
 *
 * `user: 'root'` runs as root; `'default'` runs as the VM's default user. The
 * argv is passed straight to `VMExec.run`, so quoting in individual args is
 * preserved verbatim. Any tokens or secrets must be encoded as proxy
 * placeholder strings, never resolved values.
 */
export interface PluginCommand {
  user: 'root' | 'default';
  argv: string[];
}

/**
 * Result of initializing a single plugin: low-level rules the framework
 * merges into a sandbox-wide allowlist + command list.
 *
 * - `domains` shape the proxy host allowlist.
 * - `policies` carry credential-substitution actions (allow/block + mutations).
 * - `commands` run post-lockdown (only the host proxy is reachable).
 * - `bootstrapScript` runs as root pre-lockdown, with the network open.
 * - `projectInitCwdOverride` sets the working directory for the project-level
 *   init hook (`setup-project.sh`). At most one plugin may set this per
 *   sandbox — `expandPlugins` throws on conflict.
 *
 * Environment variables for the project (e.g. `AURICA_PROJECT_DIR`) are not
 * passed here — plugins emit a root `PluginCommand` to write them into
 * `/etc/environment`, which makes them visible to every PAM-launched shell
 * (init hooks included) instead of being scoped to a single invocation.
 *
 * `bootstrapScript`, when set, is trusted code shipped in the sandbox tool's
 * source — plugin authors own its safety. Inputs interpolated into it (e.g.
 * the linux user name) must be validated first via
 * {@link assertSafeShellIdent} or equivalent.
 */
export interface InitializedPlugin {
  domains: string[];
  policies: ProxyPolicy[];
  commands: PluginCommand[];
  bootstrapScript?: string;
  projectInitCwdOverride?: string;
}

/**
 * Resolved user-config type for a plugin. When the plugin declares no
 * `userConfigSchema`, the field is typed as `undefined`; otherwise it is the
 * schema's inferred type (which may itself be `undefined` if the user-level
 * config omits this plugin's defaults).
 */
type UserConfigOf<U> = U extends z.ZodType ? z.infer<U> | undefined : undefined;

/**
 * Context passed to a plugin's `initialize` function. The framework
 * supplies:
 *
 * - `project`             — the validated project-config block for this plugin.
 * - `user`                — the validated user-config block, or `undefined` when
 *                           the plugin declares no user schema or the user-level
 *                           config omits this plugin.
 * - `generatePlaceholder` — returns a deterministic per-plugin token the proxy
 *                           uses for credential substitution. Call with a
 *                           short caller-chosen `suffix` to mint distinct
 *                           tokens within one plugin (e.g.
 *                           `generatePlaceholder('git')`,
 *                           `generatePlaceholder('gh')`). The framework folds
 *                           the plugin name in for cross-plugin uniqueness, so
 *                           two plugins using the same suffix do not collide.
 *                           Plugins that don't substitute credentials can
 *                           ignore this.
 * - `linuxUser`           — the linux user inside the VM (already validated to
 *                           be a safe shell identifier, so plugins can
 *                           interpolate it directly into bootstrap scripts).
 * - `sandboxName`         — the sandbox's registered name.
 * - `authSecret`          — the sandbox's per-run secret, generated by the
 *                           framework at create time and stored on the
 *                           sandbox's state entry. Plugins that run an on-host
 *                           service authenticated by the sandbox (e.g. the MCP
 *                           gateway) bake this directly into the artifacts
 *                           they install in the VM.
 */
export interface PluginInitContext<U, P extends z.ZodType> {
  project: z.infer<P>;
  user: UserConfigOf<U>;
  generatePlaceholder: (suffix: string) => string;
  linuxUser: string;
  sandboxName: string;
  authSecret: string;
}

/**
 * Contract every plugin implements. The plugin registry collects these into
 * a single source of truth used to build the project/user config schemas,
 * iterate plugins at expansion time, and validate placeholder uniqueness.
 *
 * `name` is the key under which the plugin appears in the keyed config shape
 * (`config.plugins.<name>`), so it must be unique across the registry. It is
 * also the discriminator used to look up a plugin's section in both project
 * and user configs.
 *
 * `projectConfigSchema` is the strict schema applied to the project-level
 * config block. Plugins that take no project-level options use
 * `z.object({})`.
 *
 * `userConfigSchema` is optional. When set, the same plugin name in the
 * user-level config is validated against it. Plugins that need no user-level
 * defaults omit this field entirely. The framework still treats project
 * declaration as the opt-in: a user-level default never activates a plugin
 * the project did not opt into.
 *
 * `initialize` runs per-plugin at sandbox-create / proxy-reload time and
 * returns the low-level rules the framework merges across plugins.
 */
export interface SandboxPlugin<
  U extends z.ZodType | undefined = z.ZodType | undefined,
  P extends z.ZodType = z.ZodType,
> {
  name: string;
  projectConfigSchema: P;
  /**
   * Always present in the type — set to `undefined` when the plugin needs
   * no user-level defaults. Keeping the property required (rather than
   * optional) lets `Extract<…, { userConfigSchema: z.ZodType }>` cleanly
   * pick out the plugins that do declare a user schema.
   */
  userConfigSchema: U;
  initialize(ctx: PluginInitContext<U, P>): InitializedPlugin;

  /**
   * Register CLI subcommands. Called once at CLI startup, regardless of
   * whether any project has opted into the plugin — host-side commands
   * like `aurica-sandbox mcp login <server>` must work without a project
   * config loaded.
   *
   * The hook may be async so plugins can dynamic-import their command
   * modules to avoid registry-load cycles. Each hook is awaited before
   * the CLI parses `process.argv`, so subcommands are guaranteed to be
   * registered by the time the user's command runs.
   *
   * Plugins that don't contribute CLI commands omit this. Order of
   * invocation follows the registry's declared order.
   */
  cliCommands?(program: Command, ctx: CliCommandContext): void | Promise<void>;

  /**
   * Return a long-running sidecar handle to be colocated with the proxy
   * daemon. Invoked once at proxy boot, after `HostProxy` is listening.
   * The handle's `stop()` is awaited during proxy shutdown.
   *
   * Plugins without a sidecar omit this. Returning `null` (e.g. because
   * the user has not configured the plugin) is a valid way to opt out at
   * runtime without throwing.
   */
  proxySidecar?(ctx: SidecarContext): Promise<ProxySidecar | null>;
}

/**
 * Context passed to `plugin.cliCommands`. The framework injects loaders
 * that plugins would otherwise have to dynamic-import to dodge the
 * plugin-registry init cycle (plugin files are loaded *during*
 * registry init, but `config/user.ts` reads back into the registry
 * via `userPluginsSchema`). The CLI entry point lives outside the
 * cycle and can value-import these loaders freely; passing them
 * through context lets plugins use plain top-level imports for
 * everything else.
 *
 * Loaders are thunks (not pre-loaded values) so they only run when
 * the active subcommand actually needs them — `mcp --help` shouldn't
 * touch disk.
 */
export interface CliCommandContext {
  loadUserConfig: () => Promise<UserConfig>;
}

/**
 * Context passed to `plugin.proxySidecar`. Carries a live view of the
 * sandbox registration set plus framework-side loaders/mutators the
 * sidecar needs at runtime — injected for the same cycle-avoidance
 * reason described on {@link CliCommandContext}.
 *
 * `loadSandboxConfig` is a per-projectDir loader because the sidecar
 * re-reads each sandbox's `.aurica/sandbox.json` whenever the
 * registration set changes; bundling a static map would race the
 * watcher.
 */
export interface SidecarContext {
  loadUserConfig: () => Promise<UserConfig>;
  loadSandboxConfig: (projectDir: string) => Promise<SandboxConfig>;
  sandboxes: SandboxRegistrationStream;
  /**
   * Shared credential resolver: same instance the host proxy uses for
   * `replace-header` mutations. Sidecars that resolve credential
   * sources (`env:VAR`, `gh-token`, …) should use this so a token is
   * cached once across the proxy + every plugin sidecar.
   */
  credentialResolver: { resolve(rawSource: string): Promise<string> };
}

/**
 * Long-running sidecar handle returned by `plugin.proxySidecar`.
 * `runProxyProcess` retains the handle and awaits `stop()` on shutdown
 * (SIGINT/SIGTERM or programmatic stop).
 */
export interface ProxySidecar {
  stop(): Promise<void>;
}

/**
 * Live view of the proxy's sandbox registration set delivered to sidecars.
 * Subscribers receive the current snapshot synchronously when they call
 * `subscribe`, then a fresh snapshot on every change.
 *
 * The snapshot is a plain array (rather than the live state object) so
 * sidecars cannot accidentally mutate the proxy's bookkeeping.
 */
export interface SandboxRegistrationStream {
  /**
   * Returns the current snapshot of registered sandboxes.
   */
  snapshot(): readonly SandboxEntry[];
  /**
   * Subscribe to changes. The listener fires once immediately with the
   * current snapshot, then on every subsequent change. Returns an
   * `unsubscribe` function.
   */
  subscribe(listener: (snapshot: readonly SandboxEntry[]) => void): () => void;
}
